
# all path can be relatif or absolute
DATA: 
    REFERENCE:       "/path/to/reference_file.fasta"   #reference genome (fasta file) only if INSIDER_VARIANT = True [optional]
    GENOME:          "/path/to/genome_file.fasta"      #genome (fasta file) [required]
    SAMPLE:          "/path/to/reads_file.fastq"       #long reads (a fastq file) only if OUTSIDER_VARIANT = True [optional]
    WORK_DIRECTORY:  "/path/to/directory_work"         #name of output directory [required or empty]
    TE_DB:           "/path/to/database_TE.fasta"      #Database of TE (a fasta file) [required]



CHOICE:
    PIPELINE:
        OUTSIDER_VARIANT: True  # TE no assembled (out of genome)
        INSIDER_VARIANT: True   # TE assembled (in genome)
        REPORT: True            # for getting report.html with graph
    OUTSIDER_VARIANT:
        LOCAL_ASSEMBLY:
            FLYE: False # (True, False)
            WTDGB: False # (True, False)
        CALL_SV: "svim" # possibility (sniffles, svim) 
        INTEGRATE_TE_TO_GENOME: True # (True, False) xxx
        OPTIMIZE_FREQUENCE: True # (True, False) xxx
    INTERMEDIATE_FILE: True     # to keep the intermediate analysis files to process them. 


PARAMS:
    OUTSIDER_VARIANT:
        MINIMAP2:
            PRESET_OPTION: 'map-ont' # minimap2 preset option is map-ont by default (map-pb, map-ont etc)
            OPTION: '-t 8' # more option of minimap2
        SAMTOOLS_VIEW:
            PRESET_OPTION: '' 
        SAMTOOLS_SORT:
            PRESET_OPTION: ''
        SAMTOOLS_CALLMD:
            PRESET_OPTION: ''
        FLYE:
            OPTIONS: '--plasmids -t 8' #
            PRESET_OPTION: '--nano-raw' # 
        TSD:
            FILE_SIZE_TE_TSD: "/path/to/SIZE_TSD.txt" # path file or empty value [optional]
            SIZE_FLANK: 30  # flanking sequence size to calculate TSD put value > 4 
        TE_DETECTION:
            CHROM_KEEP: "." # regular expresion of chromosome; exemple  for Drosophila  "[23][RL],4,X" ; Put "." for keep all chromosome
        INTEGRATE_TE_TO_GENOME:
            PUT_ID: True # (True, False) xxx
            PUT_SEQUENCE_DB_TE: True # (True, False) xxx
        PARS_BLN_OPTION: "--min-size-percent 90 --min-pident 94" # option of TrEMOLO/pipeline/lib/python/parse_blast_main.py d'ont put -c option
    INSIDER_VARIANT:
        PARS_BLN_OPTION: "--min-size-percent 80 --min-pident 80" 
        
        