
# all path can be relatif or absolute
DATA: 
    REFERENCE:       "/path/to/reference_file.fasta"   #reference genome (fasta file) only if INSIDER_VARIANT = True [optional]
    GENOME:          "/path/to/genome_file.fasta"      #genome (fasta file) [required]
    WORK_DIRECTORY:  "TrEMOLO_OUTPUT"                   #name of output directory [required or empty]
    TE_DB:           "/path/to/database_TE.fasta"      #Database of TE (a fasta file) [required]



CHOICE:
    PIPELINE:
        OUTSIDER_VARIANT: False  # D'ont change it
        INSIDER_VARIANT: True   # TE assembled (in genome)
        REPORT: True            # for getting report.html with graph
