
# all path can be relatif or absolute
DATA: 
    REFERENCE:       "/path/to/reference_file.fasta"   #reference genome (fasta file) only if INSIDER_VARIANT = True [optional]
    GENOME:          "/path/to/genome_file.fasta"      #genome (fasta file) [required]
    WORK_DIRECTORY:  "TrEMOLO_OUTPUT"                  #name of output directory [required or empty]
    TE_DB:           "/path/to/database_TE.fasta"      #Database of TE (a fasta file) [required]


CHOICE:
    PIPELINE:
        OUTSIDER_VARIANT: False # D'ont change it
        INSIDER_VARIANT: True   # TE assembled (in genome)
        REPORT: True            # for getting report.html with graph
    OUTSIDER_VARIANT:
        CALL_SV: "sniffles" # possibility (sniffles, svim) 
        INTEGRATE_TE_TO_GENOME: True # (True, False) Re-build the assembly with insiders integrated in
        OPTIMIZE_FREQUENCE: True # (True, False) FREQUENCE CALCULATE WITH CLIPPING READS
        CLIPPED_READS: False # (True, False) Processing of clipped reads (SOFT, HARD)
    INSIDER_VARIANT:
        DETECT_ALL_TE: False    # Warning can take long time
    INTERMEDIATE_FILE: True     # to keep the intermediate analysis files to process them. 


PARAMS:
    THREADS: 8 #number of threads for some task
    OUTSIDER_VARIANT:
        MINIMAP2:
            PRESET_OPTION: 'map-ont' # minimap2 preset option is map-ont by default (map-pb, map-ont etc)
            OPTION: '' # more option of minimap2
        SAMTOOLS_VIEW:
            PRESET_OPTION: '' 
        SAMTOOLS_SORT:
            PRESET_OPTION: ''
        SAMTOOLS_CALLMD:
            PRESET_OPTION: ''
        TSD:
            SIZE_FLANK: 20  # flanking sequence size to calculate TSD put value > 4 
        TE_DETECTION:
            CHROM_KEEP: "." # regular expresion of chromosome; exemple  for Drosophila  "[23][RL],4,X" ; Put "." for keep all chromosome
            GET_SEQ_REPORT_OPTION: "-m 30" #option get_seq_vcf.py option du fichier de récupération des séquences dans le vcf
        PARS_BLN_OPTION: "--min-size-percent 80 --min-pident 80" # option of TrEMOLO/pipeline/lib/python/parse_blast_main.py  Warning d'ont put -c option
    INSIDER_VARIANT:
        PARS_BLN_OPTION: "--min-size-percent 80 --min-pident 80" 
        
        