var data = [
{TEname: "R2-element", reverse: -0, forward: 1},
{TEname: "Max-element", reverse: -0, forward: 1},
{TEname: "Transpac", reverse: -0, forward: 1},
{TEname: "diver", reverse: -1, forward: 1},
{TEname: "17.6", reverse: -0, forward: 1},
{TEname: "opus", reverse: -2, forward: 2},
{TEname: "mdg3", reverse: -4, forward: 1},
{TEname: "G2", reverse: -0, forward: 1},
{TEname: "springer", reverse: -0, forward: 1},
{TEname: "Doc", reverse: -5, forward: 1},
{TEname: "gtwin", reverse: -0, forward: 1},
{TEname: "gypsy", reverse: -0, forward: 1},
{TEname: "HMS-Beagle", reverse: -0, forward: 1},
{TEname: "copia", reverse: -1, forward: 0},
{TEname: "F-element", reverse: -2, forward: 1},
{TEname: "ZAM", reverse: -2, forward: 1},
{TEname: "Quasimodo", reverse: -1, forward: 0},
{TEname: "412", reverse: -3, forward: 0},
{TEname: "blood", reverse: -0, forward: 3},
{TEname: "297", reverse: -0, forward: 1},
{TEname: "invader4", reverse: -2, forward: 0},
{TEname: "roo", reverse: -5, forward: 0}
]
