--- 
title: "MINI REPORT"
author: ""
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
description: "mini report of analysis of TrEMOLO"
---



# REPORT TrEMOLO ANALYSIS

```{r, echo=FALSE}
#install.packages("bookdown")
# or the development version
# devtools::install_github("rstudio/bookdown")
knitr::opts_chunk$set(engine.path = list(python='/usr/bin/python3'), echo=FALSE, message=FALSE, cache=FALSE, include=TRUE, results=FALSE, eval=TRUE)
```

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```

```{r, eval=TRUE, include=TRUE, results=FALSE}

library(ggplot2)
library(dplyr)
library(reshape2)
library(kableExtra)
library(forcats)# pour reorder
library(RColorBrewer)
library(ggthemes)
library(rjson)
library(viridisLite)
library(viridis)

```

## Resume parameters


```{r, eval=TRUE, include=TRUE, results=TRUE}

params <- fromJSON(file="../../params.log", method='C')

print(paste("REFERENCE : ", params$DATA$REFERENCE))
print(paste("GENOME : ", params$DATA$GENOME))
print(paste("TE DATABASE : ", params$DATA$TE_DB))
print(paste("SAMPLE : ", params$DATA$SAMPLE))
print(paste("WORKING DIRECTORY : ", params$DATA$WORK_DIRECTORY))
print(paste("VARIANT CALLING : ", params$CHOICE$OUTSIDER_VARIANT$CALL_SV))

```



<!-- ## TE ANALYSIS
 -->

